version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/hannuri/static/frontend
    overwrite: yes

permissions:
  - object: /
    pattern: "**"

hooks:
  ApplicationStart:
    - location: script/try.sh
