name: CI-CD-Frontend

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - "frontend/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          echo ${{ vars.TEST_ECHO }}
          echo ${{ secrets.TEST_SECRET }}
        shell: bash
