name: CI-CD-Frontend

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - "frontend/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          echo ${{ env.TEST_ECHO }}
        shell: bash
